### PR TITLE
Add failing test creating an object in a fiber

### PR DESCRIPTION
**Pull request by kelunik**
This adds a minimal test case from the segfault in https://github.com/amphp/byte-stream/tree/ext-fiber.

### CODE REVIEW

**Comment by martinschroeder** [comment]
Hi, is just tested that case and it does fail for me. I do get an error because class `Foobar` is not defined. If i change the code to create an instance of `Message` instead the test passes.

```
---- EXPECTED OUTPUT
START
END
---- ACTUAL OUTPUT
START

Fatal error: Uncaught Error: Class 'Foobar' not found in /vagrant/tests/036-create-object-with-ctor-in-fiber.php:12
Stack trace:
#0 [internal function]: {closure}()
#1 /vagrant/tests/036-create-object-with-ctor-in-fiber.php(16): Fiber->start()
#2 {main}
  thrown in /vagrant/tests/036-create-object-with-ctor-in-fiber.php on line 12
---- FAILED
```

**Comment by kelunik** [comment]
Do you use the latest `php-src` @ `master`?

**Comment by martinschroeder** [comment]
No, i re-creataed my vagrant machine for testing a few days ago. I will rebuild from current master and try again. Testing against PHP master is very unreliable, i never know if anything segfaults due to my changes in fiber-ext or something changed in PHP core. I might look into testing using a stable PHP 7.2 release with the fiber patch applied to avoid this...

**Comment by kelunik** [comment]
@martinschroeder I know. I think the segfault started happening after the GC issues were fixed, but I didn't confirm this, yet.

**Comment by martinschroeder** [comment]
I rebuilt the machine from current PHP master and used fiber-ext master (without any changes except for adding the additional test case): the test case still works for me...

I am running `amphp/byte-stream` test cases to see where it segfaults and the problem seems to be related to autoloading (include or require a file from within a running fiber to be precise). I can run tests using `phpdbg` with `-vrr` options enabled and it segfault when an `INCLUDE_OR_EVAL` opcode is executed in a fiber.

**Comment by martinschroeder** [comment]
@kelunik you can run all `byte-stream` test cases without segfault after my latest commit. For skipped test cases: half of them failed due to calling `await()` instead of `wait()`, once you strip the leading `a` they work just fine.

**Comment by kelunik** [comment]
@martinschroeder No, `await()` is correct there, it's just a missing import. Tests work all fine now. :+1:

**Pull request closed without merging**
